#!/usr/bin/env bash
# sidecars/build-interceptor.sh
#
# Assemble the single all-providers interceptor file from each provider's
# interceptor.py block. The result is mounted into user application containers
# via PYTHONSTARTUP (one ConfigMap in kube-system, copied per-namespace by the
# webhook). Each block fail-soft skips if its SDK is not importable, so the one
# file works in any quantum container regardless of which vendor SDK is present.
#
# Run from the repo root or sidecars/.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/fluence_quantum_intercept.py"

{
  echo "# fluence_quantum_intercept.py — GENERATED by build-interceptor.sh"
  echo "# All-providers interceptor. Do not edit by hand; edit the per-provider"
  echo "# providers/<name>/interceptor.py blocks and re-run build-interceptor.sh."
  echo "#"
  echo "# Mounted via PYTHONSTARTUP into user application containers. Each block"
  echo "# fail-soft skips if its vendor SDK is not importable in this container."
  echo ""
  for block in "$HERE"/providers/*/interceptor.py; do
    name="$(basename "$(dirname "$block")")"
    echo ""
    echo "# ─── provider: $name ─────────────────────────────────────────────"
    cat "$block"
  done
} > "$OUT"

echo "wrote $OUT"
